version: "3.9"

services:
  app:
    image: .
    working_dir: /app
    volumes:
      - sqlite_data:/app/db_data
    ports:
      - "8080:8080"
    environment:
      LISTENING_ADDRESS: "0.0.0.0"
      HTTP_PORT: 8080
      GIN_MODE: "release"

volumes:
  sqlite_data:
