package handlers

import (
	"crypto/sha256"
	"encoding/hex"
	"net/http"

	"github.com/gin-gonic/gin"
)

func computeSHA256Hash(text string) string {
	hash := sha256.Sum256([]byte(text))
	return hex.EncodeToString(hash[:])
}

// PUT /objects/{bucket}/{objectID}
// this is a terrible pattern since users are not supposed to decide the objectID
// In a real-world scenario, the objectID should be generated by the server and returned to the user.

func (dbh *DBHandler) PutObject(ctx *gin.Context) {
	var req ApiRequestGetPutDelete

	if err := ctx.ShouldBindUri(&req); err != nil {
		ctx.JSON(http.StatusBadRequest, ResponseTemplatePutDelete{
			Message: "Invalid request",
			Error:   err.Error(),
		})
		return
	}

	var reqBody ApiRequestPutBody
	if err := ctx.ShouldBindJSON(&reqBody); err != nil {
		ctx.JSON(http.StatusBadRequest, ResponseTemplatePutDelete{
			Bucket:   req.Bucket,
			ObjectID: req.ObjectID,
			Message:  "Invalid request body",
			Error:    err.Error(),
		})
		return
	}

	bucket := req.Bucket
	objectID := req.ObjectID
	content := reqBody.Content

	sha256_hash := computeSHA256Hash(content)

	// first of all let's check if the bucket exists
	rowsBucketbyID, err := dbh.DB.QueryContext(ctx, "SELECT id FROM buckets WHERE id = ?", bucket)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to check bucket existence",
			Error:    err.Error(),
		})
		return
	}
	rowsBucketbyIDExists := rowsBucketbyID.Next()
	rowsBucketbyID.Close()

	// if the bucket does not exist, create it
	if !rowsBucketbyIDExists {
		_, err = dbh.DB.ExecContext(ctx, "INSERT INTO buckets (id) VALUES (?)", bucket)
		if err != nil {
			ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
				Bucket:   bucket,
				ObjectID: objectID,
				Message:  "Failed to create bucket",
				Error:    err.Error(),
			})
			return
		}
	}

	// check if the object already exists

	rowsExistingObject, err := dbh.DB.QueryContext(ctx, "SELECT id FROM objects WHERE (id = ? OR sha256_hash = ?) AND bucket_id = ?", objectID, sha256_hash, bucket)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to check object existence",
			Error:    err.Error(),
		})
		return
	}
	rowsExistingObjectExists := rowsExistingObject.Next()
	rowsExistingObject.Close()

	if rowsExistingObjectExists {
		ctx.JSON(http.StatusConflict, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "An object with the same content already exists in the bucket",
			Error:    "Object already exists",
		})
		return
	}

	// if the object does not exist, store it in the database

	_, err = dbh.DB.ExecContext(ctx, "INSERT INTO objects (id, bucket_id, content, sha256_hash) VALUES (?, ?, ?, ?)", objectID, bucket, content, sha256_hash)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to store object",
			Error:    err.Error(),
		})
		return
	}

	ctx.JSON(http.StatusCreated, ResponseTemplatePutDelete{
		Bucket:   bucket,
		ObjectID: objectID,
		Message:  "Object stored successfully",
		Error:    "",
	})
}
