package handlers

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"net/http"

	"github.com/rs/zerolog/log"

	"github.com/gin-gonic/gin"
)

func computeSHA256Hash(text string) string {
	hash := sha256.Sum256([]byte(text))
	return hex.EncodeToString(hash[:])
}

// PUT /objects/{bucket}/{objectID}
// this is a terrible pattern since users are not supposed to decide the objectID
// In a real-world scenario, the objectID should be generated by the server and returned to the user.

func (gh *GenericHTTPHandler) PutObject(ctx *gin.Context) {
	var req ApiRequestGetPutDelete

	if err := ctx.ShouldBindUri(&req); err != nil {
		log.Error().Err(err).Msg("Failed to bind URI parameters")
		ctx.JSON(http.StatusBadRequest, ResponseTemplatePutDelete{
			Bucket:   req.Bucket,
			ObjectID: req.ObjectID,
			Message:  "Invalid request",
		})
		return
	}

	var reqBody ApiRequestPutBody
	if err := ctx.ShouldBindJSON(&reqBody); err != nil {
		log.Error().Err(err).Msg("Failed to bind request body")
		ctx.JSON(http.StatusBadRequest, ResponseTemplatePutDelete{
			Bucket:   req.Bucket,
			ObjectID: req.ObjectID,
			Message:  "Invalid request body",
		})
		return
	}

	bucket := req.Bucket
	objectID := req.ObjectID
	content := reqBody.Content

	sha256_hash := computeSHA256Hash(content)

	// first of all let's check if the bucket exists
	log.Debug().Msgf("Checking if bucket %s exists...", bucket)
	bucketObj, err := gh.DBHandler.GetBucketByID(ctx, bucket)

	if err != nil && err != sql.ErrNoRows {
		log.Error().Err(err).Msgf("Failed to check bucket existence for bucket %s", bucket)
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to check bucket existence",
		})
		return
	}

	// if the bucket does not exist, create it
	if bucketObj == nil {
		log.Info().Msgf("Bucket %s does not exist. Creating it...", bucket)
		err = gh.DBHandler.InsertBucket(ctx, bucket)

		if err != nil {
			log.Error().Err(err).Msgf("Failed to create bucket %s", bucket)
			ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
				Bucket:   bucket,
				ObjectID: objectID,
				Message:  "Failed to create bucket",
			})
			return
		}
	}

	// check if the object already exists
	log.Debug().Msgf("Checking if object with ID %s in bucket %s already exists...", objectID, bucket)
	objectExists, err := gh.DBHandler.CheckObjectExistance(ctx, bucket, objectID, sha256_hash)

	if err != nil {
		log.Error().Err(err).Msgf("Failed to check object existence for bucket %s and object ID %s", bucket, objectID)
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to check object existence",
		})
		return
	}

	if objectExists {
		log.Warn().Msgf("Object with ID %s in bucket %s already exists", objectID, bucket)
		ctx.JSON(http.StatusConflict, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "An object with the same content already exists in the bucket",
		})
		return
	}

	// if the object does not exist, store it in the database

	err = gh.DBHandler.InsertObject(ctx, objectID, bucket, content, sha256_hash)

	if err != nil {
		log.Error().Err(err).Msgf("Failed to store object with ID %s in bucket %s", objectID, bucket)
		ctx.JSON(http.StatusInternalServerError, ResponseTemplatePutDelete{
			Bucket:   bucket,
			ObjectID: objectID,
			Message:  "Failed to store object",
		})
		return
	}

	log.Info().Msgf("Successfully stored object with ID %s in bucket %s", objectID, bucket)
	ctx.JSON(http.StatusCreated, ResponseTemplatePutDelete{
		Bucket:   bucket,
		ObjectID: objectID,
		Message:  "Object stored successfully",
	})
}
